### ISSUE TITLE
Support for the algorithms' usage frequency

### ISSUE THREAD

**Issue by Entoryvekum** [spencerchubb/algdb#15]
Speed cube database used to display the number of times that a algorithm is used in solutions reconstructed. I believe supporting this feature will provide a great convenience for us to choose proper algorithms. Also, given the difficulty in implement, vote system similar to the current speedcubedb is also a good option.

**Comment by spencerchubb** [comment]
I think what you're getting at is basically a way to help people find high-quality algorithms as easily as possible. There are a couple approaches:
1. Use a voting system so the best algs are surfaced to the top
2. Ensure that every algorithm in the database is high-quality

I tend to prefer the second option (make every alg high-quality). That way users know that any alg they see on cubingapp is suitable for speedsolving, and they can decide which one they want to use

Furthermore some algs may be better for one-handed, big cubes, influencing edge orientation, influencing corner permutation, etc. I don't think a voting system would capture that very well.

I'm always open to discussion though!

**Comment by Entoryvekum** [comment]
I believe your idea is better. Providing more algorithms will also encourage the explore of new options and increase the diversity of algorithms that are put in to usage in actual solving.
